### register 
POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "name": "Testeur",
    "email": "test@mail.com",
    "phone": "+237657857548",
    "password": "password123"
    

}

### login
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email":"super@admin.com",
    "password":"Super123!"
}