@baseUrl = http://localhost:3001/api
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZWRkZDE0NS1jNGJjLTQwYzctODE4YS1kOTljN2U4ZmFkZDciLCJlbWFpbCI6InN1cGVyQGFkbWluLmNvbSIsInJvbGUiOiJTVVBFUiIsImlhdCI6MTc2NzgyNjQ4MCwiZXhwIjoxNzY4NDMxMjgwfQ.4vkM1qdHcHQIf0GAqnrmdnoeXAumdpJAxzx3C6Df_Bc
@productId =87b74624-c2ad-4755-a109-ec771ae3e9da

### orders
POST http://localhost:3001/api/orders
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "deliveryName": "Test Client",
  "deliveryPhone": "237657857548",
  "deliveryAddress": "Douala, Akwa",
  "items": [
    {
      "productId": "87b74624-c2ad-4755-a109-ec771ae3e9da",
      "quantity": 1
    }
  ]
}

### 🔐 Créer un produit (ADMIN)
POST {{baseUrl}}/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Cake au choclat",
  "description": "Délicieux  ",
  "price": 300,
  "category": "patisserie",
  "stock": 300,
  "available": true
}

### 📦 Récupérer tous les produits
GET {{baseUrl}}/products

### 📦 Récupérer les produits par catégorie
GET {{baseUrl}}/products?category=patisserie

### 📦 Récupérer les produits disponibles
GET {{baseUrl}}/products?available=true

### ⭐ Récupérer les produits les plus likés
GET {{baseUrl}}/products/most-liked?limit=5

### 🔍 Récupérer un produit par ID
GET {{baseUrl}}/products/{{productId}}

### ✏️ Mettre à jour un produit (ADMIN)
PATCH {{baseUrl}}/products/{{productId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "price": 5000,
  "stock": 15,
  "available": true
}

###  Liker un produit
POST {{baseUrl}}/products/{{productId}}/like

###  Supprimer un produit (ADMIN)
DELETE {{baseUrl}}/products/{{productId}}
Authorization: Bearer {{token}}

### Upluader une image pour un produit (ADMIN)
POST http://localhost:3001/api/products/3f69634f-db14-4b86-b1d5-fd977fc48f1d/images
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="cake.png"
Content-Type: image/png

< ./test-images/cake.png
------WebKitFormBoundary
Content-Disposition: form-data; name="isFeatured"

true
------WebKitFormBoundary
Content-Disposition: form-data; name="altText"

Gâteau délicieux
------WebKitFormBoundary
Content-Disposition: form-data; name="order"

0
------WebKitFormBoundary--